services:
  api-dev:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: students_api_dev
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - APP_ENV=development
    volumes:
      - .:/code
    restart: always

  api-prod:
    build: .
    container_name: students_api_prod
    ports:
      - '8080:8000'
    env_file:
      - .env
    environment:
      - APP_ENV=production
    volumes:
      - ./data:/code/data
    restart: always
